# Generated by Django 5.2.7 on 2025-11-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_he', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.StoreProduct', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['store', 'product'], name='storeproduct_store_product_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproduct',
            index=models.Index(fields=['product', 'store'], name='storeproduct_product_store_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('product', 'store')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_he'], name='product_name_he_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name_en'], name='product_name_en_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='product_brand_cat_idx'),
        ),
    ]
