# Generated by Django 5.2.7 on 2025-11-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 1.50 (liters) or 2.00 (kg)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_unit_type',
            field=models.CharField(blank=True, help_text='e.g., liter, kilogram, unit', max_length=30),
        ),
    ]
