# Generated by Django 5.2.7 on 2025-11-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_unit_type_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_unit_type',
            field=models.CharField(blank=True, help_text='Deprecated: legacy single-language field retained for compatibility.', max_length=30),
        ),
    ]
