# Generated by Django 5.2.7 on 2025-11-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '__first__'),
        ('whatsapp', '0005_remove_wauser_intro_delivery_ts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('units_in_price', models.PositiveSmallIntegerField(default=1, help_text='Number of units covered by the reported price (e.g., 3 for a 3-pack deal).')),
                ('min_cart_total', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required to redeem the deal (e.g., 100 for orders over 100₪).', max_digits=7, null=True)),
                ('deal_notes', models.CharField(blank=True, help_text='Free-text qualifier for other deal conditions (e.g., loyalty-only, coupons).', max_length=240)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('product_text_raw', models.CharField(blank=True, max_length=240)),
                ('wa_message_id', models.CharField(blank=True, max_length=128)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(default='whatsapp', max_length=40)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.wauser')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'store', 'observed_at'], name='pr_product_store_time_idx'), models.Index(fields=['store', 'observed_at'], name='pr_store_time_idx'), models.Index(fields=['product', 'observed_at'], name='pr_product_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('last_observed_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'product'], name='sps_store_product_idx'), models.Index(fields=['product', 'store'], name='sps_product_store_idx')],
                'unique_together': {('product', 'store')},
            },
        ),
    ]
