# Generated by Django 5.2.7 on 2025-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='is_for_club_members_only',
            field=models.BooleanField(default=False, help_text='Whether the deal is restricted to loyalty/club members.'),
        ),
    ]
