# Generated by Django 5.2.7 on 2025-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricereport_is_for_club_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='needs_moderation',
            field=models.BooleanField(db_index=True, default=True, help_text='True until a moderator validates the report.'),
        ),
    ]
