# Generated by Django 5.2.7 on 2025-11-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricereport_needs_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last moderation action.', null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last moderated this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_price_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='moderation_reason',
            field=models.CharField(blank=True, help_text='Optional reason or note recorded by the moderator (e.g., rejection cause).', max_length=240),
        ),
    ]
