# Generated by Django 5.2.7 on 2025-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_pricereport_moderated_at_pricereport_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductsnapshot',
            name='confirmation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of approved user reports confirming this price.'),
        ),
    ]
