# Generated by Django 5.2.7 on 2025-11-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_storeproductsnapshot_confirmation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereport',
            name='unit_measure_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity per unit (e.g., 1.50 liters, 2.00 kg).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pricereport',
            name='unit_measure_type',
            field=models.CharField(blank=True, help_text='Unit type (liter, kilogram, piece, etc.).', max_length=30),
        ),
    ]
