# Generated by Django 5.2.7 on 2025-11-02 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WAUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_id_hash', models.CharField(max_length=64, unique=True)),
                ('wa_last4', models.CharField(blank=True, help_text='Support-only lookup; do not store full number', max_length=4, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('locale', models.CharField(default='he-IL', max_length=10)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('tz', models.CharField(default='Asia/Jerusalem', max_length=64)),
                ('consent_ts', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WA User',
                'verbose_name_plural': 'WA Users',
                'indexes': [models.Index(fields=['last_seen'], name='whatsapp_wa_last_se_9faeca_idx')],
            },
        ),
    ]
