# Generated by Junie on 2025-11-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wauser',
            name='intro_sent_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
