# Generated by Junie on 2025-11-03
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_wauser_intro_sent_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wauser',
            name='intro_session_started_ts',
            field=models.DateTimeField(blank=True, null=True, help_text='Start of 24h intro session window'),
        ),
    ]
