# Generated by Junie on 2025-11-04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_wauser_intro_session_started_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wauser',
            name='intro_last_msg_id',
            field=models.CharField(max_length=128, blank=True, null=True, help_text='Last WhatsApp intro message id sent'),
        ),
        migrations.AddField(
            model_name='wauser',
            name='intro_delivery_ts',
            field=models.DateTimeField(blank=True, null=True, help_text='When the latest intro message was delivered/read'),
        ),
    ]
