# Generated by Django 5.2.7 on 2025-11-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_wauser_intro_delivery_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wauser',
            name='intro_delivery_ts',
        ),
        migrations.RemoveField(
            model_name='wauser',
            name='intro_last_msg_id',
        ),
        migrations.RemoveField(
            model_name='wauser',
            name='intro_sent_ts',
        ),
        migrations.RemoveField(
            model_name='wauser',
            name='intro_session_started_ts',
        ),
    ]
