# Generated by Django 5.2.7 on 2025-11-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_remove_wauser_intro_delivery_ts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('store', 'store'), ('city', 'city'), ('product', 'product'), ('price', 'price'), ('units', 'units'), ('club', 'club'), ('limit', 'limit'), ('cart', 'cart'), ('complete', 'complete'), ('canceled', 'canceled')], default='store', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_sessions', to='whatsapp.wauser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='whatsapp_de_user_id_33d5f8_idx'), models.Index(fields=['updated_at'], name='whatsapp_de_updated_c147e3_idx')],
            },
        ),
    ]
