# Generated by Django 5.2.7 on 2025-11-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_dealreportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='wauser',
            name='wa_number',
            field=models.CharField(blank=True, help_text='Digits-only WhatsApp ID (E.164); used for proactive notifications.', max_length=32),
        ),
    ]
