# Generated by Django 5.2.7 on 2025-11-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_wauser_wa_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealLookupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('product', 'product'), ('location', 'location'), ('complete', 'complete'), ('canceled', 'canceled')], default='product', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_lookup_sessions', to='whatsapp.wauser')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='whatsapp_de_user_id_16ffb7_idx'), models.Index(fields=['updated_at'], name='whatsapp_de_updated_6331b8_idx')],
            },
        ),
    ]
