# Generated by Django 5.2.7 on 2025-11-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_deallookupsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealreportsession',
            name='step',
            field=models.CharField(choices=[('store', 'store'), ('city', 'city'), ('product', 'product'), ('price', 'price'), ('units', 'units'), ('club', 'club'), ('unit_type', 'unit_type'), ('unit_quantity', 'unit_quantity'), ('limit', 'limit'), ('cart', 'cart'), ('complete', 'complete'), ('canceled', 'canceled')], default='store', max_length=20),
        ),
    ]
