# Generated by Django 5.2.7 on 2025-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0012_alter_deallookupsession_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealreportsession',
            name='step',
            field=models.CharField(choices=[('store', 'store'), ('branch', 'branch'), ('city', 'city'), ('store_confirm', 'store_confirm'), ('product', 'product'), ('brand', 'brand'), ('unit_type', 'unit_type'), ('unit_quantity', 'unit_quantity'), ('price', 'price'), ('units', 'units'), ('club', 'club'), ('limit', 'limit'), ('cart', 'cart'), ('complete', 'complete'), ('canceled', 'canceled')], default='store', max_length=20),
        ),
    ]
