# Generated by Django 5.2.7 on 2025-11-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='store',
            name='name_he',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='storechain',
            name='name_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='storechain',
            name='name_he',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
