# Generated by Django 5.2.7 on 2025-11-17 09:18

import json
import re
from django.db import migrations, models
from psycopg.types.json import Json


def _clean_aliases(values):
    seen = set()
    cleaned = []
    for value in values or []:
        text = (value or "").strip()
        if not text or text in seen:
            continue
        cleaned.append(text)
        seen.add(text)
    return cleaned


def _normalize_store_text(value):
    text = (value or "").strip().lower()
    if not text:
        return ""
    return re.sub(r"[^0-9a-z\u0590-\u05ff]+", "", text)


_HEBREW_DOUBLE_MAP = {
    "וו": "ו",
    "יי": "י",
}


def _expand_normalized_variants(token: str) -> set[str]:
    if not token:
        return set()
    variants = {token}
    for source, target in _HEBREW_DOUBLE_MAP.items():
        next_variants = set(variants)
        for existing in variants:
            if source in existing:
                next_variants.add(existing.replace(source, target))
        variants = next_variants
    return variants


def _build_search_terms(values):
    terms = []
    seen = set()
    for value in values:
        normalized = _normalize_store_text(value)
        for variant in _expand_normalized_variants(normalized):
            if not variant or variant in seen:
                continue
            terms.append(variant)
            seen.add(variant)
    return terms


def _coerce_list(value):
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, str):
        try:
            data = json.loads(value)
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            return []
    return []


def populate_search_terms(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT id, name, name_he, name_en, display_name,
                   name_aliases_he, name_aliases_en
            FROM stores_store
            """
        )
        rows = cursor.fetchall()

    updates = []
    for row in rows:
        (
            store_id,
            name,
            name_he,
            name_en,
            display_name,
            aliases_he_raw,
            aliases_en_raw,
        ) = row
        aliases_he = _clean_aliases(_coerce_list(aliases_he_raw))
        aliases_en = _clean_aliases(_coerce_list(aliases_en_raw))
        terms = _build_search_terms(
            [name, name_he, name_en, display_name] + aliases_he + aliases_en
        )
        updates.append(
            (aliases_he, aliases_en, terms, store_id)
        )

    if not updates:
        return

    with connection.cursor() as cursor:
        for aliases_he, aliases_en, terms, store_id in updates:
            cursor.execute(
                """
                UPDATE stores_store
                SET name_aliases_he = %s::jsonb,
                    name_aliases_en = %s::jsonb,
                    name_search_terms = %s::jsonb
                WHERE id = %s
                """,
                [Json(aliases_he), Json(aliases_en), Json(terms), store_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_city_city_obj'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE stores_store "
                        "DROP COLUMN IF EXISTS name_aliases_en;"
                        "ALTER TABLE stores_store "
                        "ADD COLUMN name_aliases_en jsonb NOT NULL DEFAULT '[]'::jsonb"
                    ),
                    reverse_sql="ALTER TABLE stores_store DROP COLUMN IF EXISTS name_aliases_en",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='store',
                    name='name_aliases_en',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE stores_store "
                        "DROP COLUMN IF EXISTS name_aliases_he;"
                        "ALTER TABLE stores_store "
                        "ADD COLUMN name_aliases_he jsonb NOT NULL DEFAULT '[]'::jsonb"
                    ),
                    reverse_sql="ALTER TABLE stores_store DROP COLUMN IF EXISTS name_aliases_he",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='store',
                    name='name_aliases_he',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE stores_store "
                        "DROP COLUMN IF EXISTS name_search_terms;"
                        "ALTER TABLE stores_store "
                        "ADD COLUMN name_search_terms jsonb NOT NULL DEFAULT '[]'::jsonb"
                    ),
                    reverse_sql="ALTER TABLE stores_store DROP COLUMN IF EXISTS name_search_terms",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='store',
                    name='name_search_terms',
                    field=models.JSONField(blank=True, default=list),
                ),
            ],
        ),
        migrations.RunPython(populate_search_terms, migrations.RunPython.noop),
    ]
